import type * as monaco from "monaco-editor";

export const THEME_NAME = "catppuccin-mocha";

export const catppuccinMochaTheme: monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "cdd6f4" },
    { token: "comment", foreground: "6c7086", fontStyle: "italic" },
    { token: "keyword", foreground: "cba6f7" },
    { token: "string", foreground: "a6e3a1" },
    { token: "number", foreground: "fab387" },
    { token: "regexp", foreground: "f5c2e7" },
    { token: "type", foreground: "f9e2af" },
    { token: "class", foreground: "f9e2af" },
    { token: "function", foreground: "89b4fa" },
    { token: "variable", foreground: "cdd6f4" },
    { token: "variable.predefined", foreground: "f38ba8" },
    { token: "constant", foreground: "fab387" },
    { token: "operator", foreground: "89dceb" },
    { token: "tag", foreground: "cba6f7" },
    { token: "attribute.name", foreground: "f9e2af" },
    { token: "attribute.value", foreground: "a6e3a1" },
    { token: "delimiter", foreground: "9399b2" },
    { token: "delimiter.bracket", foreground: "9399b2" },
    { token: "meta", foreground: "f5c2e7" },
  ],
  colors: {
    "editor.background": "#1e1e2e",
    "editor.foreground": "#cdd6f4",
    "editor.lineHighlightBackground": "#313244",
    "editor.selectionBackground": "#585b7066",
    "editor.inactiveSelectionBackground": "#585b7033",
    "editorCursor.foreground": "#f5e0dc",
    "editorWhitespace.foreground": "#585b7066",
    "editorIndentGuide.background": "#31324480",
    "editorIndentGuide.activeBackground": "#585b70",
    "editorLineNumber.foreground": "#6c7086",
    "editorLineNumber.activeForeground": "#cdd6f4",
    "editorBracketMatch.background": "#585b7033",
    "editorBracketMatch.border": "#585b70",
    "editorGutter.background": "#1e1e2e",
    "editorOverviewRuler.border": "#313244",
    "editorWidget.background": "#181825",
    "editorWidget.border": "#313244",
    "editorSuggestWidget.background": "#181825",
    "editorSuggestWidget.border": "#313244",
    "editorSuggestWidget.selectedBackground": "#313244",
    "editorHoverWidget.background": "#181825",
    "editorHoverWidget.border": "#313244",
    "input.background": "#313244",
    "input.border": "#45475a",
    "input.foreground": "#cdd6f4",
    "scrollbar.shadow": "#11111b",
    "scrollbarSlider.background": "#585b7066",
    "scrollbarSlider.hoverBackground": "#585b70",
    "scrollbarSlider.activeBackground": "#7f849c",
    "minimap.background": "#1e1e2e",
    "minimapSlider.background": "#585b7033",
    "minimapSlider.hoverBackground": "#585b7066",
    "diffEditor.insertedTextBackground": "#a6e3a120",
    "diffEditor.removedTextBackground": "#f38ba820",
    "diffEditor.insertedLineBackground": "#a6e3a110",
    "diffEditor.removedLineBackground": "#f38ba810",
  },
};
